tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "git"

cask "adobe-acrobat-reader"

cask "flux"

cask "google-backup-and-sync"

cask "hermes"

cask "keepingyouawake"

cask "microsoft-teams"

cask "spectacle"

cask "google-chrome"